apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitec-scrapy-server-deployment
  namespace: digitec-scrapy-server
  labels:
    app: digitec-scrapy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digitec-scrapy-server
  template:
    metadata:
      labels:
        app: digitec-scrapy-server
    spec:
      containers:
        - name: digitec-scrapy-server
          image: lukzimmermann/digitec_scrapy_server:latest
          ports:
            - containerPort: 8000
          env:
            - name: CLEAN_JOB_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: CLEAN_JOB_INTERVAL
            - name: ZIP_JOB_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: ZIP_JOB_INTERVAL
            - name: ZIP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: ZIP_SIZE
            - name: SCRAP_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: SCRAP_INTERVAL
            - name: BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: BATCH_SIZE
            - name: BASELINE_PATH
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: BASELINE_PATH
            - name: BASELINE_ZIP_PATH
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: BASELINE_ZIP_PATH
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: DATA_PATH
            - name: CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  name: digitec-scrapy-server-config
                  key: CONFIG_PATH
          volumeMounts:
            - name: nfs-volume
              mountPath: /app/data
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: digitec-scrapy-server-pv
---
apiVersion: v1
kind: Service
metadata:
  name: digitec-scrapy-server-service
  namespace: digitec-scrapy-server
spec:
  type: NodePort
  selector:
    app: digitec-scrapy-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30400
