apiVersion: v1
kind: PersistentVolume
metadata:
  name: digitec-scrapy-server-pv
  namespace: digitec-scrapy-server # Adding the namespace here
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/user/digitecScrapyData
    server: 10.0.20.10
