apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digitec-scrapy-server-pv
  namespace: digitec-scrapy-server
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi
