apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-homeautomation
  namespace: databases
  labels:
    app: postgres-homeautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-homeautomation
  template:
    metadata:
      labels:
        app: postgres-homeautomation
    spec:
      containers:
        - name: postgres-homeautomation
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: databases-secrets
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: databases-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: databases-secrets
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: TZ
              value: Europe/Zurich
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-homeautomation-service
  namespace: databases
spec:
  type: NodePort
  selector:
    app: postgres-homeautomation
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30300
