apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-db
  namespace: monitoring
  labels:
    app: influx-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx-db
  template:
    metadata:
      labels:
        app: influx-db
    spec:
      containers:
        - name: influx-db
          image: influxdb:2
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DOCKER_INFLUXDB_INIT_USERNAME
                  name: influx-db-secret
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
                  name: influx-db-secret
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: Homelab
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: Monitoring
          volumeMounts:
            - name: influx-db-data
              mountPath: /var/lib/influxdb2
            - name: influx-db-data
              mountPath: /etc/influxdb2
      volumes:
        - name: influx-db-data
          persistentVolumeClaim:
            claimName: influx-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influx-db-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: influx-db
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30800
