apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-db-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
